export const GET_LIST_PROVEEDORES_SUCCESS = 'GET_LIST_PROVEEDORES_SUCCESS';
export const GET_LIST_PROVEEDORES_FAIL = 'GET_LIST_PROVEEDORES_FAIL';
export const GET_PROVEEDOR_SUCCESS = 'GET_PROVEEDOR_SUCCESS';
export const GET_PROVEEDOR_FAIL = 'GET_PROVEEDOR_FAIL';