export const GET_LIST_PRODUCTOS_SUCCESS = 'GET_LIST_PRODUCTOS_SUCCESS';
export const GET_LIST_PRODUCTOS_FAIL = 'GET_LIST_PRODUCTOS_FAIL';
export const GET_LIST_PRODUCTOS_PROVEEDOR_SUCCESS = 'GET_LIST_PRODUCTOS_PROVEEDOR_SUCCESS';
export const GET_LIST_PRODUCTOS_PROVEEDOR_FAIL = 'GET_LIST_PRODUCTOS_PROVEEDOR_FAIL';
export const GET_PRODUCTO_SUCCESS = 'GET_PRODUCTO_SUCCESS';
export const GET_PRODUCTO_FAIL = 'GET_PRODUCTO_FAIL';
export const SEARCH_PRODUCTO_SUCCESS = 'SEARCH_PRODUCTO_SUCCESS';
export const SEARCH_PRODUCTO_FAIL = 'SEARCH_PRODUCTO_FAIL';