export const GET_LIST_PRODUCTOS_SUCCESS = 'GET_LIST_PRODUCTOS_SUCCESS';
export const GET_LIST_PRODUCTOS_FAIL = 'GET_LIST_PRODUCTOS_FAIL';
export const GET_LIST_PRODUCTOS_PROVEEDOR_SUCCESS = 'GET_LIST_PRODUCTOS_PROVEEDOR_SUCCESS';
export const GET_LIST_PRODUCTOS_PROVEEDOR_FAIL = 'GET_LIST_PRODUCTOS_PROVEEDOR_FAIL';