export const GET_LIST_COMPRAS_SUCCESS = 'GET_LIST_COMPRAS_SUCCESS';
export const GET_LIST_COMPRAS_FAIL = 'GET_LIST_COMPRAS_FAIL';
export const GET_COMPRA_SUCCESS = 'GET_COMPRA_SUCCESS';
export const GET_COMPRA_FAIL = 'GET_COMPRA_FAIL';