export const GET_LIST_VENTAS_SUCCESS = 'GET_LIST_VENTAS_SUCCESS';
export const GET_LIST_VENTAS_FAIL = 'GET_LIST_VENTAS_FAIL';
export const GET_VENTA_SUCCESS = 'GET_VENTA_SUCCESS';
export const GET_VENTA_FAIL = 'GET_VENTA_FAIL';
export const SEARCH_VENTA_SUCCESS = 'SEARCH_VENTA_SUCCESS';
export const SEARCH_VENTA_FAIL = 'SEARCH_VENTA_FAIL';