export const GET_LIST_CLIENTES_SUCCESS = 'GET_LIST_CLIENTES_SUCCESS';
export const GET_LIST_CLIENTES_FAIL = 'GET_LIST_CLIENTES_FAIL';
export const GET_CLIENTE_SUCCESS = 'GET_CLIENTE_SUCCESS';
export const GET_CLIENTE_FAIL = 'GET_CLIENTE_FAIL';