export const GET_LIST_SERVICIOS_SUCCESS = 'GET_LIST_SERVICIOS_SUCCESS';
export const GET_LIST_SERVICIOS_FAIL = 'GET_LIST_SERVICIOS_FAIL';
export const GET_SERVICIO_SUCCESS = 'GET_SERVICIO_SUCCESS';
export const GET_SERVICIO_FAIL = 'GET_SERVICIO_FAIL';
export const SEARCH_SERVICIO_SUCCESS = 'SEARCH_SERVICIO_SUCCESS';
export const SEARCH_SERVICIO_FAIL = 'SEARCH_SERVICIO_FAIL';
export const GET_LIST_CATEGORIAS_SUCCESS = 'GET_LIST_CATEGORIAS_SUCCESS';
export const GET_LIST_CATEGORIAS_FAIL = 'GET_LIST_CATEGORIAS_FAIL';